Error on refresh with UTCAttribute in python 2.7
    self._model.refresh()
  File "/usr/local/lib/python2.7/dist-packages/pynamodb/models.py", line 360, in refresh
    args, kwargs = self._get_save_args(attributes=False)
  File "/usr/local/lib/python2.7/dist-packages/pynamodb/models.py", line 346, in _get_save_args
    serialized = self.serialize(null_check=null_check)
  File "/usr/local/lib/python2.7/dist-packages/pynamodb/models.py", line 391, in serialize
    serialized = attr.serialize(value)
  File "/usr/local/lib/python2.7/dist-packages/pynamodb/attributes.py", line 258, in serialize
    fmt = Delorean(value, timezone=UTC).datetime.strftime(DATETIME_FORMAT)
  File "/usr/local/lib/python2.7/dist-packages/delorean/dates.py", line 175, in __init__
    if not is_datetime_naive(datetime):
  File "/usr/local/lib/python2.7/dist-packages/delorean/dates.py", line 30, in is_datetime_naive
    if dt.tzinfo is None:
AttributeError: 'unicode' object has no attribute 'tzinfo'